-- SupabaseのSQL Editorに貼り付けて実行するSQLです。
-- 学習用なので、ログインしていない人もカフェ一覧は見られる設定にしています。

create table if not exists cafes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id) on delete cascade,
  name text not null,
  address text not null,
  lat double precision not null,
  lng double precision not null,
  comment text,
  hours text,
  wifi text default '不明',
  power text default '不明',
  parking text default '不明',
  like_count integer default 0
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  cafe_id bigint references cafes(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  body text not null
);

alter table cafes enable row level security;
alter table comments enable row level security;

drop policy if exists "cafes_select_all" on cafes;
drop policy if exists "cafes_insert_login" on cafes;
drop policy if exists "cafes_update_own" on cafes;
drop policy if exists "cafes_update_login" on cafes;
drop policy if exists "cafes_delete_own" on cafes;

create policy "cafes_select_all" on cafes
for select using (true);

create policy "cafes_insert_login" on cafes
for insert with check (auth.uid() = user_id);

-- 学習用に、ログイン済みユーザーはいいね数などを更新できるようにしています。
-- 画面上では、自分が登録したカフェだけ編集・削除ボタンを表示します。
create policy "cafes_update_login" on cafes
for update using (auth.uid() is not null)
with check (auth.uid() is not null);

create policy "cafes_delete_own" on cafes
for delete using (auth.uid() = user_id);

drop policy if exists "comments_select_all" on comments;
drop policy if exists "comments_insert_login" on comments;
drop policy if exists "comments_delete_own" on comments;

create policy "comments_select_all" on comments
for select using (true);

create policy "comments_insert_login" on comments
for insert with check (auth.uid() = user_id);

create policy "comments_delete_own" on comments
for delete using (auth.uid() = user_id);
